#!/usr/bin/guile
!#

(import (sph) (sph documentation) (sph io) (srfi srfi-1) (sph alist) (sph list))
(define highlights (file->datums "other/highlights"))

(define module-info
  (module-find-one-information-sorted "modules/sph" #:load-path (list (string-append (getcwd) "/modules"))))

(apply-values
  (l (highlights other) (display-line "## highlights")
    (display-module-information-short highlights #t) (display-line "\n## other")
    (display-module-information-short other #t))
  (partition (l (a) (list-index-value highlights (alist-ref a (q name)))) module-info))
